config/routes.rb
Rails.application.routes.draw do
  #resources :sales # enable later when admin is set up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  devise_for 	:users,
  				path: '',
  				path_names: {
  				  sign_in: 'login',
  				  sign_out: 'logout',
  				  edit: 'profile'
  				},
  				controllers: {
  				  omniauth_callbacks: 'omniauth_callbacks',
  				  registrations: 'registrations'

  				}

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => 'phone_numbers#verify'
  post 'provide_services' => 'pages#provide_services'
  #post 'about_me' => 'pages#about_me' not needed

  resources :users, only: [:show, :destroy] do
    get 'delete-account' => 'users#delete_account'
    resources :reviews, only: [:destroy]
    # For Braintree merchant creation
    #resources :merchants, only: [:new, :create]
  end



  resources :photos

  resources :gig_categories do
    resources :gig_sub_categories do
      resources :gigs
    end
  end

  resources :gigs, only: [:show, :edit, :update, :destroy, :index] do
    #resources :reviews, only: [:create, :destroy]
    resources :offers, only: [:create, :index, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    # member do
    #   post :cancel
    # end
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :offers do
    # braintree routes
    # resources :transactions, only: [:new, :create]
    member do
      post :inactivate
      post :accept
      post :reject
      post :sign_off
    end
  end

  #resources :after_signup


  # stripe routes
  # get  '/buy/:offer_id', to: 'transactions#new',      as: :show_buy
  # post '/buy/:offer_id', to: 'transactions#create',   as: :buy
  # get  '/pickup/:guid',   to: 'transactions#pickup',   as: :pickup
  # get '/auth/stripe_connect/callback', to: 'stripe_connect#create'
  # mount StripeEvent::Engine => '/stripe-events'

  # braintree webhooks
  # match 'webhooks/process' => 'webhooks#handle',
  #   :as => :process_webhook, :via => :post
  # match 'webhooks/process' => 'webhooks#verify',
  #   :as => :verify_webhook, :via => :get



  # mount Sidekiq::Web => '/sidekiq'

  # post 'bank_details' => 'bank_details#create'
  # get 'bank_details' => 'bank_details#show'


  # get '/preload' => 'offers#preload'
  # get '/preview' => 'offers#preview'

  # get '/your_trips' => 'offers#your_trips'
  get '/dashboard' => 'offers#dashboard'
  get '/your-purchases' => 'offers#your_purchases'

  # post '/notify' => 'offers#notify'
  # post '/your_trips' => 'offers#your_trips'

  get 'how_it_works_layout_test' => 'pages#how_it_works_layout_test'
  #get 'pages/gigs' => 'pages#gigs'
  #get '/lawncare' => 'pages#lawncare'
  get '/howitworks' => 'pages#howitworks'
  #get '/housework' => 'pages#housework'
  #get '/other' => 'pages#other'
  get '/search' => 'pages#search'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/terms' => 'pages#terms'


  # Twilio
  post 'tokens' => "tokens#create"
end

app/models/gig_sub_category.rb
class GigSubCategory < ActiveRecord::Base
    extend FriendlyId
    friendly_id :name, use: [:slugged, :history]

    belongs_to :gig_category
    has_many :gigs
end

app/controllers/gig_sub_categories_controller.rb
class GigSubCategoriesController < ApplicationController


    def show
        @gig_sub_category = GigSubCategory.friendly.find(params[:id])
    end

    def index
        @gig_category = GigCategory.friendly.find(params[:gig_category_id])
        @gig_sub_categories = GigSubCategory.where(gig_category_id: GigCategory.friendly.find(params[:gig_category_id]))
    end
end

app/views/gig_sub_categories/index.html.haml
= content_for :body do
  class="blue-background"
- @gig_sub_categories.each do |sub_category|
  .col-lg-6
    .panel.panel-default
      .panel-body
        .thumb.pull-left
          = link_to new_gig_category_gig_sub_category_gig_path(sub_category.gig_category, sub_category) do
            = image_tag "#{sub_category.name.split[0]}thumb.png", class: "gig-thumb"
        .caption
          %h3.task-header= sub_category.name
          %p.task-description= sub_category.description
          %br/
          = link_to "Select", new_gig_category_gig_sub_category_gig_path(sub_category.gig_category, sub_category), class: "btn btn-success btn-lg"
    / end panel-body
  / end panel

app/views/gig_sub_categories/show.html.haml
/ <haml_silent> case GigCategory.find(params[:gig_category_id]).name </haml_silent><haml_block>
/ </haml_block><haml_silent> when &quot;Yard Work&quot; </haml_silent><haml_block>
/ <haml_silent> case GigSubCategory.find(params[:id]).name </haml_silent><haml_block>
/ </haml_block><haml_silent> when &quot;Lawn Mowing&quot; </haml_silent><haml_block>
/ <haml_loud> render partial: &#39;gigs/forms/lawnmowingform&#39; </haml_loud>
/ </haml_block><haml_silent> when &quot;Leaf Raking&quot; </haml_silent><haml_block>
/ <haml_loud> render partial: &#39;gigs/forms/leafrakingform&#39; </haml_loud>
/ </haml_block><haml_silent> when &quot;Gardening&quot; </haml_silent><haml_block>
/ <haml_loud> render partial: &#39;gigs/forms/gardeningform&#39; </haml_loud>
/ </haml_block><haml_silent> else </haml_silent><haml_block>
/ <haml_loud> render partial: &#39;gigs/forms/otherform&#39; </haml_loud>
/ </haml_block>
/ </haml_block><haml_silent> when &quot;House Work&quot; </haml_silent><haml_block>
/ </haml_block><haml_silent> when &quot;Cleaning&quot; </haml_silent><haml_block>
/ </haml_block><haml_silent> else </haml_silent><haml_block>
/ <haml_loud> render :partial =&gt; &#39;gigs/forms/otherform&#39; </haml_loud>
/ </haml_block>

app/views/gig_sub_categories/show1.html.haml
= @gig_sub_category.name
.panel.panel-default
  .panel-heading
    What do you need done?
  .panel-body
    .container.gig
      = simple_form_for Gig.new do |f|
        = f.hidden_field :gig_category_id, value: params[:gig_category_id]
        = f.hidden_field :gig_sub_category_id, value: params[:id]
        = f.hidden_field :active, value: true
        .row.form-div
          .col-md-12
            %h4 Give your gig a title
            = f.input :name, label: false,            |
              placeholder: "Be clear and descriptive" |
        .row.form-div
          .col-md-12
            %h4.form-header How big is your lawn?
            %hr.form-divider/
            %ul.list-inline.gig-radios
              .col-md-4
                %li
                  = f.input :user_var1, label: false, as: :radio_buttons, collection: ["Small"], checked: "Small"
              .col-md-4
                %li
                  = f.input :user_var1, label: false, as: :radio_buttons, collection: ["Medium"]
              .col-md-4
                %li
                  = f.input :user_var1, label: false, as: :radio_buttons, collection: ["Large"]
        .row.form-div
          .col-md-12
            %h4 How long does it normally take you to mow your lawn?
            %hr.form-divider/
            %ul.list-inline.gig-radios
              .col-md-3
                %li
                  = f.input :user_var2, label: false, as: :radio_buttons, collection: ["Under 1 Hour"], checked: "Under 1 Hour"
              .col-md-3
                %li
                  = f.input :user_var2, label: false, as: :radio_buttons, collection: ["1 to 2 Hours"]
              .col-md-3
                %li
                  = f.input :user_var2, label: false, as: :radio_buttons, collection: ["2 Hours or More"]
              .col-md-3
                %li
                  = f.input :user_var2, label: false, as: :radio_buttons, collection: ["Not Sure"]
        .row.form-div
          .col-md-12
            %h4 What would you like the runner to bring?
            %hr.form-divider/
            %ul.list-inline.gig-radios
              .col-md-3
                %li
                  = f.input :is_extra1, label: "Lawnmower", as: :boolean
              .col-md-3
                %li
                  = f.input :is_extra2, label: "Bags", as: :boolean
              .col-md-3
                %li
                  = f.input :is_extra3, label: "Weed Whacker", as: :boolean
              .col-md-3
                %li
                  = f.input :user_var4, label: "Hedge Trimmer", as: :boolean
        .row.form-div
          .col-md-12
            %h4 Summary
            = f.input :summary, label: false, placeholder: "Tell us all about your gig. You should be descriptive enough to allow people to make accurate bids.", |
              input_html: { rows: 5 }                                                                                                                             |
        .row.form-div
          .col-md-8
            %h4 Address
            = f.input :address, label: false, placeholder: "What's your address?"
          .col-md-4
            %h4 Zip code
            = f.input :zip_code, label: false, placeholder: "What's your zip?"
        .row.form-div
          .col-md-6.col-md-offset-3.text-center
            %label
              Take a picture of your lawn! Photos are
              %strong strongly
              recommended so that
              you get accurate estimates.
            %span.btn.btn-default.btn-file
              %i.fa.fa-cloud-upload.fa-lg
              Upload Photos
              \#{file_field_tag "images[]", type: :file, multiple: true}
        %br/
        %br/
        .row
          .col-md-6.col-md-offset-3.text-center
            = f.submit "Post it!", class: "btn btn-success btn-lg wide fill"
        #photos= render 'photos/list'
        %br/