config/routes.rb
Rails.application.routes.draw do
  #resources :sales # enable later when admin is set up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  devise_for 	:users,
  				path: '',
  				path_names: {
  				  sign_in: 'login',
  				  sign_out: 'logout',
  				  edit: 'profile'
  				},
  				controllers: {
  				  omniauth_callbacks: 'omniauth_callbacks',
  				  registrations: 'registrations'

  				}

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => 'phone_numbers#verify'
  post 'provide_services' => 'pages#provide_services'
  #post 'about_me' => 'pages#about_me' not needed

  resources :users, only: [:show, :destroy] do
    get 'delete-account' => 'users#delete_account'
    resources :reviews, only: [:destroy]
    # For Braintree merchant creation
    #resources :merchants, only: [:new, :create]
  end



  resources :photos

  resources :gig_categories do
    resources :gig_sub_categories do
      resources :gigs
    end
  end

  resources :gigs, only: [:show, :edit, :update, :destroy, :index] do
    #resources :reviews, only: [:create, :destroy]
    resources :offers, only: [:create, :index, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    # member do
    #   post :cancel
    # end
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :offers do
    # braintree routes
    # resources :transactions, only: [:new, :create]
    member do
      post :inactivate
      post :accept
      post :reject
      post :sign_off
    end
  end

  #resources :after_signup


  # stripe routes
  # get  '/buy/:offer_id', to: 'transactions#new',      as: :show_buy
  # post '/buy/:offer_id', to: 'transactions#create',   as: :buy
  # get  '/pickup/:guid',   to: 'transactions#pickup',   as: :pickup
  # get '/auth/stripe_connect/callback', to: 'stripe_connect#create'
  # mount StripeEvent::Engine => '/stripe-events'

  # braintree webhooks
  # match 'webhooks/process' => 'webhooks#handle',
  #   :as => :process_webhook, :via => :post
  # match 'webhooks/process' => 'webhooks#verify',
  #   :as => :verify_webhook, :via => :get



  # mount Sidekiq::Web => '/sidekiq'

  # post 'bank_details' => 'bank_details#create'
  # get 'bank_details' => 'bank_details#show'


  # get '/preload' => 'offers#preload'
  # get '/preview' => 'offers#preview'

  # get '/your_trips' => 'offers#your_trips'
  get '/dashboard' => 'offers#dashboard'
  get '/your-purchases' => 'offers#your_purchases'

  # post '/notify' => 'offers#notify'
  # post '/your_trips' => 'offers#your_trips'

  get 'how_it_works_layout_test' => 'pages#how_it_works_layout_test'
  #get 'pages/gigs' => 'pages#gigs'
  #get '/lawncare' => 'pages#lawncare'
  get '/howitworks' => 'pages#howitworks'
  #get '/housework' => 'pages#housework'
  #get '/other' => 'pages#other'
  get '/search' => 'pages#search'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/terms' => 'pages#terms'


  # Twilio
  post 'tokens' => "tokens#create"
end

app/views/shared/_devisemes.html.haml
- unless resource.errors.empty?
  :javascript
    <haml_silent>		 resource.errors.full_messages.each do |msg| 
    </haml_silent><haml_block>			#{msg}
    </haml_block>

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_footer.html.haml
%footer.footer
  .footer-primary
    .container-center
      %span
  .footer-secondary
    .container-center
      .col-xs-12.col-sm-12.col-lg-5
        .footer-content
          %span.brand giggity
          %br/
          %br/
          %br/
          %p
            Our mission is to help you stop wasting time on chores so you can
            get back to doing what you love.
          %p
            If you have any comments or suggestions, please send us a message.
            We're here to help.
      .col-xs-12.col-sm-6.col-lg-3.col-lg-offset-1
        .footer-content
          %h4.footer-title Legal stuff
          %ul.no-style
            %li
              = image_tag "/assets/zzz.png", class: "five"
              = link_to "Terms of Service", terms_path, class: "white"
            %li
              %i.fa.fa-lock>
                 #{link_to "Privacy Policy", privacy_policy_path, class: "white"}
      .col-xs-12.col-sm-6.col-lg-3
        .footer-content
          %h4.footer-title Connect with us!
  .footer-tertiary
    %span

app/views/shared/_message.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"
  - elsif msg.is_a?(Array)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = msg.first
      %br/
      %ul
        %li
          = msg[1..-1].join("</li><li>").html_safe

app/views/shared/_navbar.html.haml
/ primary header
%nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse.navbar-primary.navbar-material-light-blue
  .container.container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "giggity", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse.sixteen
      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{:href => "/search"}
            / <i class="fa fa-bars"></i>
            Browse Gigs
            %span.caret.hidden-md.hidden-sm.hidden-xs
          %ul.dropdown-menu
            %li
              %a{:href => "/search?utf8=%E2%9C%93&q%5Bgig_category_id_eq%5D=#{GigCategory.friendly.find("yard-work").id}"}
                %i.fa.fa-sun-o
                Yard Work
            %li
              %a{:href => "/search?utf8=%E2%9C%93&q%5Bgig_category_id_eq%5D=#{GigCategory.friendly.find("house-work").id}"}
                %i.fa.fa-home
                House Work
            %li
              %a{:href => "/search?utf8=%E2%9C%93&q%5Bgig_category_id_eq%5D=#{GigCategory.friendly.find("events").id}"}
                .events
                Events
            %li
              %a{:href => "/search?utf8=%E2%9C%93&q%5Bgig_category_id_eq%5D=#{GigCategory.friendly.find("random").id}"}
                .coins
                Random
        %li
          = link_to gig_categories_path do
            / <i class="fa fa-pencil-square-o"></i>
            Post a Gig
        %li
          = link_to howitworks_path do
            / <i class="fa fa-life-ring"></i>
            How It Works
      %ul.nav.navbar-nav.navbar-right
        - if(!user_signed_in?)
          %li= link_to "Log In", new_user_session_path
          %li= link_to "Sign Up", new_user_registration_path
        - else
          %li
            = link_to dashboard_path do
              %span.nav-icon{"data-placement" => "bottom", "data-toggle" => "tooltip", :title => "Dashboard"}
                %i.glyphicon.glyphicon-tasks
          %li
            = link_to conversations_path do
              / <haml_loud> "(#{@unread_count})" if @unread_count > 0</haml_loud>
              %span.nav-icon{"data-placement" => "bottom", "data-toggle" => "tooltip", :title => "Messages"}
                - if @unread_count > 0
                  .numberCircle.unread-message-icon= @unread_count
                %i.glyphicon.glyphicon-comment
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = image_tag current_user.avatar.url(:thumb), class: "img-circle avatar-medium"
              \ 
              \#{current_user.first_name}
              %span.caret
            %ul.dropdown-menu
              / <li><haml_loud> link_to "Your Gigs", gigs_path </haml_loud></li>
              / <li><haml_loud> link_to "Your Offers", dashboard_path </haml_loud></li>
              / <li role="separator" class="divider"></li>
              %li= link_to "View Profile", user_path(current_user)
              %li= link_to "Edit Profile", edit_user_registration_path
              %li= link_to "Log out", destroy_user_session_path, method: :delete
    / /.navbar-collapse
  / /.container-fluid
/ primary header
/ secondary navbar
/ <nav class="navbar navbar-secondary navbar-fixed-top">
/ <div class="container container-fluid">
/ Collect the nav links, forms, and other content for toggling
/ </div>
/ </nav>

app/views/shared/_sidebar.html.haml
.col-md-3
  .panel.panel-default
    .panel-body
      %ul.sidebar-list
        %li.sidebar-item= active_link_to "Dashboard", dashboard_path, class: "sidebar-link"
        / <li class="sidebar-item"><haml_loud> active_link_to &quot;Purchases&quot;, your_purchases_path, class: &quot;sidebar-link&quot; </haml_loud></li>