config/routes.rb
Rails.application.routes.draw do
  #resources :sales # enable later when admin is set up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  devise_for 	:users,
  				path: '',
  				path_names: {
  				  sign_in: 'login',
  				  sign_out: 'logout',
  				  edit: 'profile'
  				},
  				controllers: {
  				  omniauth_callbacks: 'omniauth_callbacks',
  				  registrations: 'registrations'

  				}

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => 'phone_numbers#verify'
  post 'provide_services' => 'pages#provide_services'
  #post 'about_me' => 'pages#about_me' not needed

  resources :users, only: [:show, :destroy] do
    get 'delete-account' => 'users#delete_account'
    resources :reviews, only: [:destroy]
    # For Braintree merchant creation
    #resources :merchants, only: [:new, :create]
  end



  resources :photos

  resources :gig_categories do
    resources :gig_sub_categories do
      resources :gigs
    end
  end

  resources :gigs, only: [:show, :edit, :update, :destroy, :index] do
    #resources :reviews, only: [:create, :destroy]
    resources :offers, only: [:create, :index, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    # member do
    #   post :cancel
    # end
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :offers do
    # braintree routes
    # resources :transactions, only: [:new, :create]
    member do
      post :inactivate
      post :accept
      post :reject
      post :sign_off
    end
  end

  #resources :after_signup


  # stripe routes
  # get  '/buy/:offer_id', to: 'transactions#new',      as: :show_buy
  # post '/buy/:offer_id', to: 'transactions#create',   as: :buy
  # get  '/pickup/:guid',   to: 'transactions#pickup',   as: :pickup
  # get '/auth/stripe_connect/callback', to: 'stripe_connect#create'
  # mount StripeEvent::Engine => '/stripe-events'

  # braintree webhooks
  # match 'webhooks/process' => 'webhooks#handle',
  #   :as => :process_webhook, :via => :post
  # match 'webhooks/process' => 'webhooks#verify',
  #   :as => :verify_webhook, :via => :get



  # mount Sidekiq::Web => '/sidekiq'

  # post 'bank_details' => 'bank_details#create'
  # get 'bank_details' => 'bank_details#show'


  # get '/preload' => 'offers#preload'
  # get '/preview' => 'offers#preview'

  # get '/your_trips' => 'offers#your_trips'
  get '/dashboard' => 'offers#dashboard'
  get '/your-purchases' => 'offers#your_purchases'

  # post '/notify' => 'offers#notify'
  # post '/your_trips' => 'offers#your_trips'

  get 'how_it_works_layout_test' => 'pages#how_it_works_layout_test'
  #get 'pages/gigs' => 'pages#gigs'
  #get '/lawncare' => 'pages#lawncare'
  get '/howitworks' => 'pages#howitworks'
  #get '/housework' => 'pages#housework'
  #get '/other' => 'pages#other'
  get '/search' => 'pages#search'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/terms' => 'pages#terms'


  # Twilio
  post 'tokens' => "tokens#create"
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :user
  #validates_uniqueness_of :phone_number, message: "That phone number already belongs to an existing user."

  phony_normalize :phone_number, default_country_code: 'US'
  validates :phone_number, phony_plausible: true, presence: true, uniqueness: true

  def generate_pin
    #self.pin = rand(0000..9999).to_s.rjust(4, "0")
    var = rand(1..2)
    self.pin = var == 1 ? Faker::Team.creature.downcase : Faker::StarWars.character.split[0].downcase
    save
  end

  def twilio_client
    Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def send_pin
    twilio_client.messages.create(
      to: phone_number,
      from: ENV['TWILIO_PHONE_NUMBER'],
      body: "Your code is '#{pin}'"
    )
  end

  def verify(entered_pin, current_user)
    if self.pin == entered_pin
      update(verified: true)
      update(user: current_user)
      current_user.update_attribute(:phone_confirmation, true)
    else
      self.attempts += 1
    end
    save
  end

end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user!

  def new
    if @user.phone_number && @user.phone_number.verified?
      redirect_to user_path(@user), notice: "Your phone number is already verified"
    elsif @user.phone_number
      @phone_number = @user.phone_number
    else
      @phone_number = @user.build_phone_number
    end
  end

  def create
    formatted_phone = PhonyRails.normalize_number(params[:phone_number][:phone_number], country_code: 'US')
    @phone_number = PhoneNumber.find_or_create_by(phone_number: formatted_phone)
    puts "phone number 1" + @phone_number.inspect
	  if !@phone_number.verified
	    puts "phone number 2" + @phone_number.inspect
      @phone_number.generate_pin
      @phone_number.send_pin
      # Reset attempts with new pin generation
      @phone_number.attempts = 0
      puts "attempts pre save: " + @phone_number.attempts.to_s
      @phone_number.save
      puts "attempts post save: " + @phone_number.attempts.to_s
    end

    respond_to do |format|
      format.js # render app/views/phone_number/create.js.erb
    end
  end

  def verify
    @phone_number = PhoneNumber.find_by(phone_number: params[:hidden_phone_number])
    @phone_number.verify(params[:pin], @user)
    respond_to do |format|
      format.js # render app/views/phone_number/verify.js.erb
    end
  end

  private
    def set_user!
      @user = current_user
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/create.js.haml
- if @phone_number.verified && @user == @phone_number.user
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Your phone number was already verified.")
  $('#status-box').fadeToggle()
- elsif @phone_number.verified && @user != @phone_number.user
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("That phone number is already in use with another account.")
  $('#status-box').fadeToggle()
- else
  $('#hidden_phone_number').val('#{@phone_number.phone_number}')
  $('#send-pin').hide()
  $('#verify-pin').fadeToggle()
  $('#pin').focus()

app/views/phone_numbers/new.html.haml
= content_for :body do
  class="blue-background"
#user-form.row
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading.text-center
        Verify your account
      %hr.padding-10/
      .panel-body
        %p To ensure honest reviews and create a secure and trusted environment, we ask all members to verify their accounts.
        %p We'll text a code to your cell phone for verification.
        %br/
        #status-box.alert.alert-success
          %p#status-message Status: Haven’t done anything yet
        #send-pin
          = form_for @phone_number, remote: true do |f|
            .form-group
              #phone.input-wrapper
                %span.fa.fa-mobile.fa-lg
                = f.text_field :phone_number, class: "form-control"
            %br/
            .text-center
              = f.submit "Send Code", class: "btn btn-primary", id: 'send-pin-link'
        #verify-pin
          / <h3>Enter your Code</h3>
          = form_tag phone_numbers_verify_path, remote: true do |f|
            = hidden_field_tag 'hidden_phone_number', ''
            .form-group
              #pin.input-wrapper
                %span.fa.fa-commenting-o
                = text_field_tag :pin, nil, placeholder: "Enter code", class: "form-control"
            %br/
            .text-center
              = submit_tag "Verify Code", class: "btn btn-primary"
      %br/
      .panel-footer
        %i.fa.fa-lock
        We respect your privacy. Your information is secured with 128-bit SSL encryption, and you can delete your account at any time.
#services-form.row
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading.text-center
        Would you like to provide services?
      %hr.padding-10/
      .panel-body
        %br/
        = form_tag provide_services_path, remote: true do |f|
          .row.form-div.text-center
            .col-md-6
              = submit_tag "Yep", class: "btn btn-primary btn-lg"
            .col-md-6
              = submit_tag "Nope", class: "btn btn-danger btn-lg"
#profile-done.row
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading.text-center
        Thanks for signing up!
      %hr.padding-10/
      - if current_user.first_name.length < 9
        .panel-body.text-center.relative
          = image_tag "/assets/heart.gif", class: "center img-responsive"
          .inset-text-effect-2.wide
            %span.pacifico giggity
            %br/
            = succeed "+" do
              .margin-top
            .margin-top-2
            = current_user.first_name
#services-form-about-me.row
  .col-sm-6.col-sm-offset-3
    .panel.panel-default
      .panel-heading.text-center
        Make someone want to hire you
      %hr.padding-10/
      .panel-body
        %br/
        = simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f|
          .text-center
            = image_tag @user.avatar.url(:medium), class: "avatar-large"
          %h4 1. Upload an avatar
          %p
            A friendly photo clearly showing your face is
            %span{:style => "font-style: italic"} critical
            for convincing someone to accept your offer.
          = f.file_field :avatar, type: :file, class: 'filestyle',                 |
            :'data-classButton' => 'btn btn-primary', 'data-size': 'md',           |
            :'data-input' => 'false', 'data-iconName': 'fa fa-cloud-upload fa-md', |
            :'data-buttonText' => 'Change Avatar'                                  |
          %p.italics.text-center.white Under 5 MB, .jpg, .png
          %h4
            2. Tell us about yourself
            %span#age-tooltip{"data-toggle" => "tooltip", :title => "A sentence or two goes a long way towards establishing a connection with someone"}
              %i.fa.fa-question-circle.fa-md
          / <haml_loud> f.label :description, &quot;Tell us about yourself&quot; </haml_loud>
          = f.input :description, label: false, placeholder: "E.g., Student at Wash U majoring in biology. Dog lover. Believes eating the Nutella out of the jar with your finger is perfectly acceptable.", input_html: { rows: 7 }
          .row.form-div.text-center
            .col-md-12
              = f.button :submit, "Finish", class: "btn btn-primary btn-lg"
:javascript
  $(document).on("ajaxComplete", function(event, xhr, settings) {
    var csrf_param = xhr.getResponseHeader('X-CSRF-Param');
    var csrf_token = xhr.getResponseHeader('X-CSRF-Token');
  
    if (csrf_param) {
      $('meta[name="csrf-param"]').attr('content', csrf_param);
    }
    if (csrf_token) {
      $('meta[name="csrf-token"]').attr('content', csrf_token);
    }
  });

app/views/phone_numbers/verify.js.haml
- if @phone_number.verified
  $('#verify-pin').hide()
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-success')
  $('#status-message').text('Success!')
  $('#user-form').hide()
  $('#services-form').fadeToggle()
- elsif @phone_number.attempts >= 5
  $('#verify-pin').hide()
  $('#send-pin').show()
  $('#phone_number').focus()
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Hmm... it looks like you've tried too many times. Let's resend the code.")
- else
  $('#status-box').removeClass()
  $('#status-box').addClass('alert alert-warning')
  $('#status-message').text("Sorry, that wasn't the right code.")
$('#status-box').fadeToggle()