config/routes.rb
Rails.application.routes.draw do
  #resources :sales # enable later when admin is set up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#home'

  devise_for 	:users,
  				path: '',
  				path_names: {
  				  sign_in: 'login',
  				  sign_out: 'logout',
  				  edit: 'profile'
  				},
  				controllers: {
  				  omniauth_callbacks: 'omniauth_callbacks',
  				  registrations: 'registrations'

  				}

  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => 'phone_numbers#verify'
  post 'provide_services' => 'pages#provide_services'
  #post 'about_me' => 'pages#about_me' not needed

  resources :users, only: [:show, :destroy] do
    get 'delete-account' => 'users#delete_account'
    resources :reviews, only: [:destroy]
    # For Braintree merchant creation
    #resources :merchants, only: [:new, :create]
  end



  resources :photos

  resources :gig_categories do
    resources :gig_sub_categories do
      resources :gigs
    end
  end

  resources :gigs, only: [:show, :edit, :update, :destroy, :index] do
    #resources :reviews, only: [:create, :destroy]
    resources :offers, only: [:create, :index, :edit, :update, :destroy] do
      resources :reviews, only: [:new, :create]
    # member do
    #   post :cancel
    # end
    end
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :offers do
    # braintree routes
    # resources :transactions, only: [:new, :create]
    member do
      post :inactivate
      post :accept
      post :reject
      post :sign_off
    end
  end

  #resources :after_signup


  # stripe routes
  # get  '/buy/:offer_id', to: 'transactions#new',      as: :show_buy
  # post '/buy/:offer_id', to: 'transactions#create',   as: :buy
  # get  '/pickup/:guid',   to: 'transactions#pickup',   as: :pickup
  # get '/auth/stripe_connect/callback', to: 'stripe_connect#create'
  # mount StripeEvent::Engine => '/stripe-events'

  # braintree webhooks
  # match 'webhooks/process' => 'webhooks#handle',
  #   :as => :process_webhook, :via => :post
  # match 'webhooks/process' => 'webhooks#verify',
  #   :as => :verify_webhook, :via => :get



  # mount Sidekiq::Web => '/sidekiq'

  # post 'bank_details' => 'bank_details#create'
  # get 'bank_details' => 'bank_details#show'


  # get '/preload' => 'offers#preload'
  # get '/preview' => 'offers#preview'

  # get '/your_trips' => 'offers#your_trips'
  get '/dashboard' => 'offers#dashboard'
  get '/your-purchases' => 'offers#your_purchases'

  # post '/notify' => 'offers#notify'
  # post '/your_trips' => 'offers#your_trips'

  get 'how_it_works_layout_test' => 'pages#how_it_works_layout_test'
  #get 'pages/gigs' => 'pages#gigs'
  #get '/lawncare' => 'pages#lawncare'
  get '/howitworks' => 'pages#howitworks'
  #get '/housework' => 'pages#housework'
  #get '/other' => 'pages#other'
  get '/search' => 'pages#search'
  get '/privacy-policy' => 'pages#privacy_policy'
  get '/terms' => 'pages#terms'


  # Twilio
  post 'tokens' => "tokens#create"
end

app/models/offer.rb
class Offer < ActiveRecord::Base

  extend FriendlyId
  friendly_id :offer_info, use: [:slugged, :history]

  belongs_to :gig
  belongs_to :bidder, class_name: "User", foreign_key: :user_id
  has_one :lister, class_name: "User", through: :gig
  has_one :sale
  has_many :reviews

  validates :price, presence: true, numericality:
    { only_integer: true, greater_than_or_equal_to: 5 }

  # Ensure unique offer between bidder / gig
  validates_uniqueness_of :user_id, scope: :gig_id

  scope :outstanding, -> { where(accepted: nil) }
  scope :accepted, -> { where(accepted: true) }
  scope :declined, -> { where(accepted: false) }

  def offer_info
    "#{self.gig.name.truncate_words(5).split(" ").join("-")}-with-#{self.bidder.first_name}-#{self.price}-#{SecureRandom.random_number(1_000_000).to_s(36)}"
  end

  def accept
    self.accepted = true
    save
  end

  def inactivate
    self.active = false
  end

  def reject
    self.accepted = false
    save
  end

  def purchase
    self.purchased = true
    save
  end

  def bidder_sign_off
    self.bidder_signed_off = true
    save
  end

  def lister_sign_off
    self.lister_signed_off = true
    save
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	before_action :authenticate_user!, except: [:notify]
	before_action :authenticate_user_phone!, except: [:notify]

	# def preload
	# 	gig = Gig.friendly.find(params[:gig_id])
	# 	#today = Date.today
	# 	offers = gig.offers #.where("start_date >= ? OR end_date >= ?", today, today)

	# 	#render json: offers
	# end

	# def preview
	# 	start_date = Date.parse(params[:start_date])
	# 	end_date = Date.parse(params[:end_date])

	# 	output = {
	# 		conflict: is_conflict(start_date, end_date)
	# 	}

	# 	#render json: output
	# end

	def create
		@gig = Gig.friendly.find(params[:gig_id])
		@offer = current_user.offers_made.create(offer_params)

		if @offer.save
			redirect_to @gig, notice: "Offer submitted"
			send_message_from_admin(@offer.lister.id, "#{@offer.bidder.first_name} just offered to do your gig for $#{@offer.price}!")
		else
			flash[:warning] = "Offers must be whole numbers (minimum $5)"
			redirect_to @gig
		end
	end

	def edit
		@offer = Offer.friendly.find(params[:id])
		if !current_user.id == @offer.bidder.id
			redirect_to root_path, notice: "You don't have permission to edit that offer."
		end
		if @offer
			respond_to do |format|
				# need to do format.html
				format.js
			end
		end
	end

	def update
		@offer = Offer.friendly.find(params[:id])
		@gig = @offer.gig
		if !@offer.update(offer_params)
			flash.now[:notice] = "Your offer couldn't be updated :("
			render :edit
		end
	end

	def destroy
		@offer = Offer.friendly.find(params[:id])
		if current_user && @offer.bidder == current_user
			@offer.destroy
		end
		session[:return_to] ||= request.referer
		redirect_to session.delete(:return_to)
	end

	def inactivate
		@offer = current_user.offers_made.friendly.find(params[:id])
		@offer.inactivate
		@offer.save

		respond_to do |format|
			format.html
			format.js
		end
	end


	def accept
		offer = current_user.offers_received.friendly.find(params[:id])
		offer.accept
		offer.gig.active = false
		offer.save
		other_offers = offer.gig.offers.where(accepted: nil)
		other_offers.each do |offer|
			offer.reject
			offer.save
		end
		redirect_to dashboard_path
		#params[:price] = offer.price
		# redirect_to new_offer_transaction_path(offer)
	end

	def reject
		offer = current_user.offers_received.friendly.find(params[:id])
		offer.reject
		redirect_to dashboard_path
	end

	def sign_off
		offer = Offer.friendly.find(params[:id])
		if current_user == offer.lister
			offer.lister_sign_off
			# add later when payments implemented
			send_message_from_admin(offer.bidder.id, "#{offer.lister.first_name} signed off on your work for the '#{offer.gig.name}' gig.")
			# send_message_from_admin(offer.bidder.id, "They'll be redirected to a payment screen and we'll shoot you a message when the payment goes through.")
			flash[:notice] = "Signed off on the work."
			redirect_to new_offer_transaction_path(offer.id)
		elsif current_user == offer.bidder
			offer.bidder_sign_off
			if !offer.lister_signed_off?
				# add later when payments implemented
				send_message_from_admin(offer.lister.id, "#{offer.bidder.first_name} just signed off for your '#{offer.gig.name}' gig.")
			end
			flash[:notice] = "Signed off on the work."
			redirect_to dashboard_path
		else
			flash[:alert] = "Are you sure that's your gig?"
			redirect_to root_url
		end
	end

	# protect_from_forgery except: [:notify]
	# def notify
	# 	params.permit!
	# 	status = params[:payment_status]

	# 	offer = Offer.friendly.find(params[:item_number])

	# 	if status == "Completed"
	# 		offer.update_attributes status: true
	# 	else
	# 		offer.destroy
	# 	end

	# 	render nothing: true
	# end

	# protect_from_forgery except: [:your_trips]
	# def your_trips
	# 	@trips = current_user.offers.where("status = ?", true)
	# end

	def dashboard
	  @offers_made = current_user.offers_made.where(active: true).paginate(page: params[:page], per_page: 10)
	  @offers_received = current_user.offers_received.paginate(page: params[:page], per_page: 10)
		@gigs = current_user.gigs_listing.order("created_at desc").paginate(page: params[:page], per_page: 10)

		@reviews_made = Review.where(reviewer: current_user)

		respond_to do |format|
			format.html
			format.js
		end
	end

	def your_purchases
		@offers = current_user.offers_received.where(purchased: true)
	end

	private

		def is_conflict(start_date, end_date)
			gig = Gig.find(params[:gig_id])

			check = gig.offers.where("? < start_date AND end_date < ?", start_date, end_date)
			check.size > 0? true : false
		end

		def offer_params
			params.require(:offer).permit(:start_date, :end_date, :price, :gig_id)
		end
end

app/views/offers/_form.html.1.haml
= form_for([@gig, @gig.offers.new]) do |f|
  .row
    .col-md-12.price_tag
      %span
        $#{@gig.price}
      %span.pull-right Total
  .row
    .col-md-6
      %label Check In
      = f.text_field :start_date, readonly: 'true', placeholder: 'Start Date', class: 'form-control'
    .col-md-6
      %label Check Out
      = f.text_field :end_date, readonly: 'true', placeholder: 'End Date', class: 'form-control', disabled: 'true'
  = f.hidden_field :gig_id, value: @gig.id
  = f.text_field :price, value: @gig.price
  = f.hidden_field :total, id: 'offer_total'
  %h4
    %span#message
  #preview{:style => "display: none"}
    %table.offer-table
      %tbody
        %tr
          %td Day(s)
          %td
            %span#offer_days
        %tr
          %td Total
          %td
            $
            %span#offer_sum
    %br/
  = f.submit "Book Now", id: "btn_book", class: "btn btn-primary wide", disabled: 'true'
:javascript
  function unavailable(date) {
  	dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
  	return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

  	unavailableDates = [];

  	$.ajax({
  		url: '/preload',
  		data: {'gig_id': #{@gig.id}},
  		dataType: 'json',
  		success: function(data) {

  			$.each(data, function(arrID, arrValue) {
  				for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
  					unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
  				}
  			});

  			$('#offer_start_date').datepicker({
  				dateFormat: 'dd-mm-yy',
  				minDate: 0,
  				maxDate: '3m',
  				beforeShowDay: unavailable,
  				onSelect: function(selected) {
  					$('#offer_end_date').datepicker("option", "minDate", selected);
  					$('#offer_end_date').attr('disabled', false);

  					var start_date = $(this).datepicker('getDate');
  					var end_date = $('#offer_end_date').datepicker('getDate');
  					var days = (end_date - start_date)/1000/60/60/24 + 1

  					var input = {
  						'start_date': start_date,
  						'end_date': end_date,
  						'gig_id': #{@gig.id}
  					}

  					$.ajax({
  						url: "/preview",
  						data: input,
  						success: function(data) {

  							if (data.conflict) {

  								$('#message').text("This date range is not available.");
  								$('#preview').hide();
  								$('#btn_book').attr('disabled', true);

  							} else {

  								$('#preview').show();
  								$('#btn_book').attr('disabled', false);

  								var total = days * #{@gig.price}
  								$('#offer_days').text(days);
  								$('#offer_sum').text(total);
  								$('#offer_total').val(total);
  							}
  						}
  					});
  				}
  			});

  			$('#offer_end_date').datepicker({
  				dateFormat: 'dd-mm-yy',
  				minDate: 0,
  				maxDate: '3m',
  				beforeShowDay: unavailable,
  				onSelect: function(selected) {
  					$('#offer_start_date').datepicker("option", "maxDate", selected);

  					var start_date = $('#offer_start_date').datepicker('getDate');
  					var end_date = $(this).datepicker('getDate');
  					var days = (end_date - start_date)/1000/60/60/24 + 1

  					var input = {
  						'start_date': start_date,
  						'end_date': end_date,
  						'gig_id': #{@gig.id}
  					}

  					$.ajax({
  						url: "/preview",
  						data: input,
  						success: function(data) {

  							if (data.conflict) {

  								$('#message').text("This date range is not available.");
  								$('#preview').hide();
  								$('#btn_book').attr('disabled', true);

  							} else {

  								$('#preview').show();
  								$('#btn_book').attr('disabled', false);

  								var total = days * #{@gig.price}
  								$('#offer_days').text(days);
  								$('#offer_sum').text(total);
  								$('#offer_total').val(total);
  							}
  						}
  					});

  				}
  			});
  		}
  	});

  	

  });

app/views/offers/_form.html.haml
= form_for([@gig, @gig.offers.new]) do |f|
  .row.no-margin
    .col-md-12.price_tag
      .input-group
        .input-group-addon $
        = f.text_field :price, placeholder: "Offer", class: 'form-control'
  = f.hidden_field :gig_id, value: @gig.id
  %h4
    %span#message
  = f.submit "Submit Offer", id: "btn_book", class: "btn btn-primary wide"

app/views/offers/_gigofferform.html.haml
= form_for(@offer, remote: true) do |f|
  .input-group
    #edit-addon.input-group-addon
      $
    = succeed "," do
      .form-control.text-left
    = f.text_field :price, rows: 1
.separator
  = f.submit Update, class: btn btn-primary
= link_to Delete, [@gig, @offer], method: :delete, class: btn btn-danger, |
  data: { confirm: Are you sure? }                                        |

app/views/offers/_offers_made.html.haml
.panel.panel-default
  .panel-heading
    Your offers
- @offers_made.each do |offer|
  .panel.panel-default
    .panel-body
      .row
        %div{:id => "offer-#{offer.id}"}
          .col-md-3.text-center.left
            - case offer.accepted
            - when true
              %h4.text-success
                $#{offer.price}
              %p.bg-success{:style => "padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"} Accepted
            - when false
              %h4.text-danger
                $#{offer.price}
              %p.bg-danger{:style => "padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"} Declined
            - else
              %h4.text-info
                $#{offer.price}
              %p.bg-info{:style => "padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"} Outstanding
            = time_ago_in_words(offer.created_at)
            ago
          .col-md-2.text-center
            = link_to user_path(offer.lister) do
              = image_tag offer.lister.avatar.url(:medium), class: "img-circle avatar-medium"
              %p= offer.gig.lister.first_name
              = link_to conversations_path(sender_id: current_user.id, recipient_id: offer.lister.id), method: 'post', style: "color: #fff" do
                .btn.btn-info.thin-padding.wide
                  %i.glyphicon.glyphicon-comment.msg-btn
                  / <i class="fa fa-envelope-o"></i>
          .col-md-4
            = link_to gig_path(offer.gig) do
              = image_tag offer.gig.photos[0].image.url(:thumb) if offer.gig.photos.length > 0
              %h4= offer.gig.name
              %br/
              %p= offer.gig.summary.truncate(40)
          .col-md-3.text-center
            - if offer.accepted != true
              = link_to inactivate_offer_path(offer), method: :post, remote: true do
                %span.pull-right Remove
            - elsif offer.accepted == true && offer.bidder_signed_off != true
              = link_to "Sign off", sign_off_offer_path(offer), method: :post, class: "btn btn-primary", |
                data: { confirm: "Are you sure you're ready to sign off on the work?" }                  |
            - elsif offer.accepted == true && offer.bidder_signed_off == true
              %p Signed off on work.
            - if offer.bidder_signed_off == true && offer.purchased != true
              = link_to "Pay", new_offer_transaction_path(offer), class: "btn btn-primary"
            - elsif offer.purchased == true
              %p.bg-success{:style => "padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"} Paid
              %br/
              - if !@reviews_made || !@reviews_made.find_by(offer_id: offer.id)
                = link_to "Leave a review", new_gig_offer_review_path(offer.gig, offer), class: "btn btn-primary"
              - else
                %span.average_rating{:id => "rating-offer-#{offer.id}"}
        / row
        %hr/
  :javascript
    $('#rating-offer-#{offer.id}').raty({
    	path: '/assets',
    	readOnly: true,
    	starType: 'i',
    	score: #{@reviews_made.where(offer: offer).first.star if !@reviews_made.where(offer: offer).empty?}
    });
.row.text-center
  = will_paginate @offers_made, renderer: BootstrapPagination::Rails,  inner_window: 2, outer_window: 0, next_label: "▶", previous_label: "	◀"

app/views/offers/_offers_received.html.haml
.panel.panel-default
  .panel-heading
    Your gigs
- @gigs.each do |gig|
  .panel.panel-default
    .panel-body
      .row
        .col-md-12
          = link_to gig do
            %h2= gig.name
          %p= gig.summary.truncate(50)
          - if !gig.offers.where(accepted: true).any?
            - if gig.offers.count > 0
              %p.bg-primary{:style => "display: inline-block; padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"}
                Offers received: #{gig.offers.count}
            - else
              %p.bg-info{:style => "display: inline-block; padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"}
                Offers received: #{gig.offers.count}
        / <div class="col-md-4">
        / <haml_loud> image_tag gig.photos[0].image.url(:thumb) if gig.photos.length &gt; 0 </haml_loud>
        / </div>
      %hr/
      - if gig.offers.where(accepted: true).any?
        - gig.offers.where(accepted: true).each do |offer|
          .row
            .col-md-3.text-center
              %h4.text-success
                $#{offer.price}
              %p.bg-success{:style => "display: inline-block; padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"} Offer accepted
              %br/
              = time_ago_in_words(offer.created_at)
              ago
            .col-md-2.text-center
              = link_to user_path(offer.bidder) do
                = image_tag offer.bidder.avatar.url(:medium), class: "img-circle avatar-medium"
                %br/
                %p= offer.bidder.first_name
                = link_to conversations_path(sender_id: current_user.id, recipient_id: offer.bidder.id), method: 'post', style: "color: #fff" do
                  .btn.btn-info.thin-padding.wide
                    %i.glyphicon.glyphicon-comment.msg-btn
                    / <i class="fa fa-envelope-o"></i>
            .col-md-4
            .col-md-3.text-center
              - if offer.lister_signed_off != true
                = link_to "Sign off", sign_off_offer_path(offer), method: :post, class: "btn btn-primary", |
                  data: { confirm: "Are you sure you're ready to sign off on the work?" }                  |
              - else
                %p Signed off on work.
              - if offer.lister_signed_off == true && offer.purchased != true
                = link_to "Pay", new_offer_transaction_path(offer), class: "btn btn-primary"
              - elsif offer.purchased == true
                %p.bg-success{:style => "padding-top: 5px; padding-bottom: 5px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"} Paid
                %br/
                - if !@reviews_made || !@reviews_made.find_by(offer_id: offer.id)
                  = link_to "Leave a review", new_gig_offer_review_path(offer.gig, offer), class: "btn btn-primary"
                - else
                  %span.average_rating{:id => "rating-offer-#{offer.id}"}
              :javascript
                $('#rating-offer-#{offer.id}').raty({
                          		path: '/assets',
                          		readOnly: true,
                          		starType: 'i',
                          		score: #{@reviews_made.where(offer: offer).first.star if !@reviews_made.where(offer: offer).empty?}
                          	});
          %hr/
      - elsif gig.offers.outstanding.any?
        %hr/
        - gig.offers.outstanding.each do |offer|
          .row
            .col-md-2.text-center
              %h4.text-info
                $#{offer.price}
              = time_ago_in_words(offer.created_at)
              ago
            .col-md-2.text-center
              = link_to user_path(offer.bidder) do
                = image_tag offer.bidder.avatar.url(:medium), class: "img-circle avatar-medium"
                %br/
                = offer.bidder.first_name
            .col-md-2
            .col-md-6.text-center
              = link_to "Accept", accept_offer_path(offer), method: :post,                                           |
                class: "btn btn-primary",                                                                            |
                data: { confirm: "You can only accept one offer for this gig.\n\nAre you sure you want to accept?" } |
              = link_to "Decline", reject_offer_path(offer), method: :post,      |
                class: "btn btn-danger",                                         |
                data: { confirm: "Are you sure you want to reject this offer?" } |
          %hr/
        / offers
/ gigs
.row.text-center
  = will_paginate @gigs, renderer: BootstrapPagination::Rails,  inner_window: 2, outer_window: 0, next_label: "▶", previous_label: "	◀"

app/views/offers/_updated.html.haml
%p
  Offer for $#{@gig.offers.find_by(bidder: current_user).price} submitted.
.separator
  = link_to "Edit", edit_gig_offer_path(@gig, @gig.offers.find_by(bidder: current_user)), |
    method: :get, remote: true, class: "btn btn-primary"                                  |

app/views/offers/dashboard.html.haml
= content_for :body do
  class="blue-background"
.row
  / show agar.io if nothing else to show
  - if !@offers_made.any? && !@offers_received.any? && !@gigs.any?
    .panel.panel-default
      .panel-heading
        This is your dashboard.
      %hr.padding-10/
      .panel-body
        %p But it's not very interesting without any activity. Why not make an offer?
        %br/
        / <p class="text-center"><img src="//a4.files.theultralinx.com/image/upload/MTI5MDU2ODQxNjEwMDc0NTkw.gif">
        / agar.io embed
        / <div class="miniclip-game-embed text-center hidden-xs hidden-sm" data-game-name="agar-io" data-theme="0" data-width="1100" data-height="1000" data-language="en"><a href="http://www.miniclip.com/games/agar-io/">Play Agar.io</a></div>
        / Insert this code before your </body> tag
        / <script src="//static.miniclipcdn.com/js/game-embed.js"></script>
    / else there's something to show
  - else
    = render 'shared/sidebar'
    .col-md-9
      / <haml_silent> if @offers_made.any? </haml_silent><haml_block>
      / Offers Made
      = render 'offers_made'
      / if @offers_made.any?
      / Offers Received
      - if @gigs.any?
        = render 'offers_received'
      / if !@offers_made.any? && !@offers_received.any? && !@gigs.any?
    / col-md-9
/ row

app/views/offers/edit.js.haml
$("#offer_box").html("#{escape_javascript render(partial: "gigofferform")}");

app/views/offers/inactivate.js.haml
$('#offer-#{@offer.id}').hide();

app/views/offers/update.js.haml
$("#offer_box").html("#{escape_javascript render(partial: "updated")}");

app/views/offers/your_purchases.html.haml
= content_for :body do
  class="blue-background"
.row
  = render 'shared/sidebar'
  .col-md-9
    .panel.panel-default
      .panel-heading
        Gigs
      .panel-body
        - @offers.each do |offer|
          .row
            .col-md-2
              = offer.price
            .col-md-2
              %h4= link_to offer.gig.name.truncate(50), offer.gig
            .col-md-2
              %p= offer.gig.summary.truncate(100)
            .col-md-2
              = link_to "Edit", edit_gig_path(offer.gig), class: "btn btn-primary"
            .col-md-2
              - if !offer.lister_signed_off?
                = link_to "Sign off", sign_off_offer_path(offer), method: :post, class: "btn btn-primary"
                = link_to "Cancel Gig", '#', method: :post, class: "btn btn-danger"
              - else
                %p Signed off on the work.
          %hr/

app/views/offers/your_trips.html.haml
.row
  = render 'shared/sidebar'
  .col-md-9
    .panel.panel-default
      .panel-heading
        Your Gigs
      .panel-body
        - @trips.each do |trip|
          .row
            .col-md-2
              = trip.start_date.strftime('%v')
            .col-md-6
              = link_to gig_path(trip.gig) do
                = image_tag trip.gig.photos[0].image.url(:thumb) if trip.gig.photos.length > 0
            .col-md-2
              = link_to user_path(trip.gig.user) do
                = image_tag trip.gig.user.avatar.url(:medium), class: "img-circle avatar-medium"
            .col-md-2.right
              %h4
                $#{trip.total}
          %hr/